### ISSUE TITLE
RuntimeError: uvloop does not support Windows

### ISSUE THREAD

**Issue by c0pper** [trevorhobenshield/twitter-api-client#3]
When I tried installing the package, it says   RuntimeError: uvloop does not support Windows at the moment and tries to install the previous version, constantly failing.

```
Collecting twitter-api-client
  Downloading twitter_api_client-0.4.0-py3-none-any.whl (31 kB)
Requirement already satisfied: requests in c:\users\smarotta\pycharmprojects\generic_scraper\my_env\lib\site-packages (from twitter-api-client) (2.28.2)
Collecting aiohttp
  Downloading aiohttp-3.8.4-cp310-cp310-win_amd64.whl (319 kB)
     |████████████████████████████████| 319 kB 3.3 MB/s
Collecting ujson
  Downloading ujson-5.7.0-cp310-cp310-win_amd64.whl (41 kB)
     |████████████████████████████████| 41 kB 3.2 MB/s
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting uvloop
  Downloading uvloop-0.17.0.tar.gz (2.3 MB)
     |████████████████████████████████| 2.3 MB ... 
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smarotta\PycharmProjects\generic_scraper\my_env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_8
0bd716f8c204c2fa6bf4ca3acf4967e\\setup.py'"'"'; __file__='"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_80bd716f8c204c2fa6bf4ca3acf4967e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__
file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-
base 'C:\Users\smarotta\AppData\Local\Temp\pip-pip-egg-info-vpoz9gkn'
       cwd: C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_80bd716f8c204c2fa6bf4ca3acf4967e\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_80bd716f8c204c2fa6bf4ca3acf4967e\setup.py", line 8, in <module>
      raise RuntimeError('uvloop does not support Windows at the moment')
  RuntimeError: uvloop does not support Windows at the moment
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ba/86/6dda1760481abf244cbd3908b79a4520d757040ca9ec37a79fc0fd01e2a0/uvloop-0.17.0.tar.gz#sha256=0ddf6baf9cf11a1a22c71487f39f15b2cf78eb5bde7e5b45fbb99e8a9d91b9e1 (from ht
tps://pypi.org/simple/uvloop/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading uvloop-0.16.0.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.4 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smarotta\PycharmProjects\generic_scraper\my_env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_e
0152b8be51f4e07a55d19c8d580f419\\setup.py'"'"'; __file__='"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_e0152b8be51f4e07a55d19c8d580f419\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__
file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-
base 'C:\Users\smarotta\AppData\Local\Temp\pip-pip-egg-info-y9b9bc6h'
       cwd: C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_e0152b8be51f4e07a55d19c8d580f419\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_e0152b8be51f4e07a55d19c8d580f419\setup.py", line 8, in <module>
      raise RuntimeError('uvloop does not support Windows at the moment')
  RuntimeError: uvloop does not support Windows at the moment
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ab/d9/22bbffa8f8d7e075ccdb29e8134107adfb4710feb10039f9d357db8b589c/uvloop-0.16.0.tar.gz#sha256=f74bc20c7b67d1c27c72601c78cf95be99d5c2cdd4514502b4f3eb0933ff1228 (from ht
tps://pypi.org/simple/uvloop/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading uvloop-0.15.3.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.4 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smarotta\PycharmProjects\generic_scraper\my_env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_2
849d00d40e641f6862db90b603cca78\\setup.py'"'"'; __file__='"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_2849d00d40e641f6862db90b603cca78\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__
file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-
base 'C:\Users\smarotta\AppData\Local\Temp\pip-pip-egg-info-5fxrrfsb'
       cwd: C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_2849d00d40e641f6862db90b603cca78\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_2849d00d40e641f6862db90b603cca78\setup.py", line 8, in <module>
      raise RuntimeError('uvloop does not support Windows at the moment')
  RuntimeError: uvloop does not support Windows at the moment
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/41/49/d2cdac6450430f444d3df59ccd1abc8225ea51ffcecd9ac2e36b111074a4/uvloop-0.15.3.tar.gz#sha256=905f0adb0c09c9f44222ee02f6b96fd88b493478fffb7a345287f9444e926030 (from ht
tps://pypi.org/simple/uvloop/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading uvloop-0.15.2.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.8 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smarotta\PycharmProjects\generic_scraper\my_env\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_b
c66758d41254b98ad900842110ad588\\setup.py'"'"'; __file__='"'"'C:\\Users\\smarotta\\AppData\\Local\\Temp\\pip-install-nif41etr\\uvloop_bc66758d41254b98ad900842110ad588\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__
file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-
base 'C:\Users\smarotta\AppData\Local\Temp\pip-pip-egg-info-u7jkumt5'
       cwd: C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_bc66758d41254b98ad900842110ad588\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\smarotta\AppData\Local\Temp\pip-install-nif41etr\uvloop_bc66758d41254b98ad900842110ad588\setup.py", line 8, in <module>
      raise RuntimeError('uvloop does not support Windows at the moment')
  RuntimeError: uvloop does not support Windows at the moment
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/44/6e/0cb292e4e6ee1382e2ede458f90c94b4f990b261f738403ac45cb8183bc2/uvloop-0.15.2.tar.gz#sha256=2bb0624a8a70834e54dde8feed62ed63b50bad7a1265c40d6403a2ac447bce01 (from ht
tps://pypi.org/simple/uvloop/) (requires-python:>=
```

**Comment by trevorhobenshield** [comment]
modified system platform check, should be working now

**Comment by c0pper** [comment]
Thanks, unfortunately when trying to install version 0.4.3 it still throws the same error...
