### ISSUE TITLE
how to turn off debugging?

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#65]
Hello, I love the debug and save arguments. And while setting `save=False` stops the `data` directory from being created, I'm not sure what to set the debug argument at to disable debugging

`scraper = Scraper(TW_EMAIL, TW_USERNAME, TW_PASSWORD, debug=0, save=False)`

**Comment by trevorhobenshield** [comment]
Just made some modifications, debugging should now be off by default.

To disable all logging and tqdm progress bars:

```python
scraper = Scraper(email, username, password, pbar=False)
```

**Comment by trevorhobenshield** [comment]
Thanks for catching this again, I noticed an issue with my log config. It should be fixed now in version `0.8.9`.

**Comment by reagle** [comment]
Thank you. I now only see a single warning.

```
❯ busy.py j .health .dog https://www.scientificamerican.com/article/allergic-to-your-pet-this-immunotherapy-may-help/
2023-06-06 15:52:02.091 [WARNING] ::
WARNING: This is a guest session, some endpoints cannot be accessed.
```

1. If I increase my logging [sensitivity in my program](https://github.com/reagle/thunderdell/blob/main/thunderdell.py#L732), I don't see more messages from your module. (That's okay, but didn't know if that should work.)
2. Need this warning be shown? Or perhaps only shown when the endpoint requires an authenticated user?

**Comment by bmorris-ocsd** [comment]
I think there's still an issue with the logging... Using the Search class, I occasionally get :

[error] failed to update token at flow_start
'flow_token'
[error] failed to update token at flow_instrumentation
'flow_token'
[error] failed to update token at flow_username
'flow_token'
[error] failed to update token at flow_password
'flow_token'
[error] failed to update token at flow_duplication_check
'flow_token'

I've tried setting debug=0 and not specifying debug at all, yet I still occasionally get that output of errors

**Comment by trevorhobenshield** [comment]
Yup those are print statements, debug levels are only for the logger. I've left them there by default because repeatedly generating those errors are one of the few things that Twitter does flag.

**Comment by reagle** [comment]
@trevorhobenshield were you speaking to me or @bmorris-ocsd ? Are you saying there's no way to disable the "guest session" warning?

**Comment by bmorris-ocsd** [comment]
> @trevorhobenshield were you speaking to me or @bmorris-ocsd ? Are you saying there's no way to disable the "guest session" warning?

Sorry, I didn't mean to cause confusion! :/   It seemed petty of me to open a new ticket for something that I feel like is more of a systemic issue than just localized to one module (if it's not more systemic and is its own issue, I'll certainly open a new one)

**Comment by reagle** [comment]
@bmorris-ocsd, I'm confused, but I don't know if it's because of you. 😉 I opened this issue, and still have it, so I wasn't sure why @trevorhobenshield closed it.

**Comment by bmorris-ocsd** [comment]
> 

Gotcha, I didn't even realize it was closed. I think as a workaround, I tried nullifying the stdout, doing something like this:

old_stdout = sys.stdout;

def Disable_stdout():
	sys.stdout = io.BytesIO();

def Enable_stdout():
	sys.stdout = old_stdout;

But if I recall correctly, something occurs in one of the modules that causes the stdout to be set back again meaning the output still shows. So rather than do something I really shouldn't (modifying the global stdout), I came here and started searching through the issues.
